/*
 * =============================================================================
 * Copyright 2010 Defence Science Technology Agency
 * 1 Depot Road, Defence Technology Tower A, Singapore 109679
 * All rights reserved.
 * =============================================================================
 * 
 * Project: Meeting Manager
 * Filename: GroupMtgRmMembership.java
 * Created on: 03.09.2010
 */

// Generated Sep 3, 2010 12:56:47 PM by Hibernate Tools 3.3.0.GA

package mtgmgr.entity;



/**
 * GroupMtgRmMembership generated by hbm2java
 */
public class GroupMtgRmMembership  implements java.io.Serializable {


     private GroupMtgRmMembershipId id;
     private MtgRmList mtgRmList;
     private GroupList groupList;
     private String role;

    public GroupMtgRmMembership() {
    }

    public GroupMtgRmMembership(GroupMtgRmMembershipId id, MtgRmList mtgRmList, GroupList groupList, String role) {
       this.id = id;
       this.mtgRmList = mtgRmList;
       this.groupList = groupList;
       this.role = role;
    }
   
    public GroupMtgRmMembershipId getId() {
        return this.id;
    }
    
    public void setId(GroupMtgRmMembershipId id) {
        this.id = id;
    }
    public MtgRmList getMtgRmList() {
        return this.mtgRmList;
    }
    
    public void setMtgRmList(MtgRmList mtgRmList) {
        this.mtgRmList = mtgRmList;
    }
    public GroupList getGroupList() {
        return this.groupList;
    }
    
    public void setGroupList(GroupList groupList) {
        this.groupList = groupList;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}



