/*
 * =============================================================================
 * Copyright 2010 Defence Science Technology Agency
 * 1 Depot Road, Defence Technology Tower A, Singapore 109679
 * All rights reserved.
 * =============================================================================
 * 
 * Project: Meeting Manager
 * Filename: MtgRmAgendaItemComment.java
 * Created on: 03.09.2010
 */

// Generated Sep 3, 2010 12:56:47 PM by Hibernate Tools 3.3.0.GA

package mtgmgr.entity;


import java.util.Date;

/**
 * MtgRmAgendaItemComment generated by hbm2java
 */
public class MtgRmAgendaItemComment  implements java.io.Serializable {


     private MtgRmAgendaItemCommentId id;
     private MtgRmMeeting mtgRmMeeting;
     private UserDirectory userDirectory;
     private Date datetime;
     private String content;

    public MtgRmAgendaItemComment() {
    }

    public MtgRmAgendaItemComment(MtgRmAgendaItemCommentId id, MtgRmMeeting mtgRmMeeting, UserDirectory userDirectory, Date datetime, String content) {
       this.id = id;
       this.mtgRmMeeting = mtgRmMeeting;
       this.userDirectory = userDirectory;
       this.datetime = datetime;
       this.content = content;
    }
   
    public MtgRmAgendaItemCommentId getId() {
        return this.id;
    }
    
    public void setId(MtgRmAgendaItemCommentId id) {
        this.id = id;
    }
    public MtgRmMeeting getMtgRmMeeting() {
        return this.mtgRmMeeting;
    }
    
    public void setMtgRmMeeting(MtgRmMeeting mtgRmMeeting) {
        this.mtgRmMeeting = mtgRmMeeting;
    }
    public UserDirectory getUserDirectory() {
        return this.userDirectory;
    }
    
    public void setUserDirectory(UserDirectory userDirectory) {
        this.userDirectory = userDirectory;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}



