/*
 * =============================================================================
 * Copyright 2010 Defence Science Technology Agency
 * 1 Depot Road, Defence Technology Tower A, Singapore 109679
 * All rights reserved.
 * =============================================================================
 * 
 * Project: Meeting Manager
 * Filename: MtgRmAgendaItemId.java
 * Created on: 03.09.2010
 */

// Generated Sep 3, 2010 12:56:47 PM by Hibernate Tools 3.3.0.GA

package mtgmgr.entity;



/**
 * MtgRmAgendaItemId generated by hbm2java
 */
public class MtgRmAgendaItemId  implements java.io.Serializable {


     private int meetingId;
     private int agendaNo;

    public MtgRmAgendaItemId() {
    }

    public MtgRmAgendaItemId(int meetingId, int agendaNo) {
       this.meetingId = meetingId;
       this.agendaNo = agendaNo;
    }
   
    public int getMeetingId() {
        return this.meetingId;
    }
    
    public void setMeetingId(int meetingId) {
        this.meetingId = meetingId;
    }
    public int getAgendaNo() {
        return this.agendaNo;
    }
    
    public void setAgendaNo(int agendaNo) {
        this.agendaNo = agendaNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MtgRmAgendaItemId) ) return false;
		 MtgRmAgendaItemId castOther = ( MtgRmAgendaItemId ) other; 
         
		 return (this.getMeetingId()==castOther.getMeetingId())
 && (this.getAgendaNo()==castOther.getAgendaNo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMeetingId();
         result = 37 * result + this.getAgendaNo();
         return result;
   }   


}



