/*
 * =============================================================================
 * Copyright 2010 Defence Science Technology Agency
 * 1 Depot Road, Defence Technology Tower A, Singapore 109679
 * All rights reserved.
 * =============================================================================
 * 
 * Project: Meeting Manager
 * Filename: MtgRmActionItemAssignee.java
 * Created on: 03.09.2010
 */

// Generated Sep 3, 2010 12:56:47 PM by Hibernate Tools 3.3.0.GA

package mtgmgr.entity;



/**
 * MtgRmActionItemAssignee generated by hbm2java
 */
public class MtgRmActionItemAssignee  implements java.io.Serializable {


     private int assigneeId;
     private MtgRmActionItem mtgRmActionItem;
     private UserDirectory userDirectory;

    public MtgRmActionItemAssignee() {
    }

    public MtgRmActionItemAssignee(int assigneeId, MtgRmActionItem mtgRmActionItem, UserDirectory userDirectory) {
       this.assigneeId = assigneeId;
       this.mtgRmActionItem = mtgRmActionItem;
       this.userDirectory = userDirectory;
    }
   
    public int getAssigneeId() {
        return this.assigneeId;
    }
    
    public void setAssigneeId(int assigneeId) {
        this.assigneeId = assigneeId;
    }
    public MtgRmActionItem getMtgRmActionItem() {
        return this.mtgRmActionItem;
    }
    
    public void setMtgRmActionItem(MtgRmActionItem mtgRmActionItem) {
        this.mtgRmActionItem = mtgRmActionItem;
    }
    public UserDirectory getUserDirectory() {
        return this.userDirectory;
    }
    
    public void setUserDirectory(UserDirectory userDirectory) {
        this.userDirectory = userDirectory;
    }




}



