/*
 * =============================================================================
 * Copyright 2010 Defence Science Technology Agency
 * 1 Depot Road, Defence Technology Tower A, Singapore 109679
 * All rights reserved.
 * =============================================================================
 * 
 * Project: Meeting Manager
 * Filename: MtgRmActionItem.java
 * Created on: 03.09.2010
 */

// Generated Sep 3, 2010 12:56:47 PM by Hibernate Tools 3.3.0.GA

package mtgmgr.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MtgRmActionItem generated by hbm2java
 */
public class MtgRmActionItem  implements java.io.Serializable {


     private int actionItemId;
     private MtgRmMeeting mtgRmMeeting;
     private int agendaNo;
     private String item;
     private String status;
     private Date dueDate;
     private Set<MtgRmActionItemNote> mtgRmActionItemNotes = new HashSet<MtgRmActionItemNote>(0);
     private Set<MtgRmActionItemAssignee> mtgRmActionItemAssignees = new HashSet<MtgRmActionItemAssignee>(0);

    public MtgRmActionItem() {
    }

	
    public MtgRmActionItem(int actionItemId, MtgRmMeeting mtgRmMeeting, int agendaNo, String item, String status) {
        this.actionItemId = actionItemId;
        this.mtgRmMeeting = mtgRmMeeting;
        this.agendaNo = agendaNo;
        this.item = item;
        this.status = status;
    }
    public MtgRmActionItem(int actionItemId, MtgRmMeeting mtgRmMeeting, int agendaNo, String item, String status, Date dueDate, Set<MtgRmActionItemNote> mtgRmActionItemNotes, Set<MtgRmActionItemAssignee> mtgRmActionItemAssignees) {
       this.actionItemId = actionItemId;
       this.mtgRmMeeting = mtgRmMeeting;
       this.agendaNo = agendaNo;
       this.item = item;
       this.status = status;
       this.dueDate = dueDate;
       this.mtgRmActionItemNotes = mtgRmActionItemNotes;
       this.mtgRmActionItemAssignees = mtgRmActionItemAssignees;
    }
   
    public int getActionItemId() {
        return this.actionItemId;
    }
    
    public void setActionItemId(int actionItemId) {
        this.actionItemId = actionItemId;
    }
    public MtgRmMeeting getMtgRmMeeting() {
        return this.mtgRmMeeting;
    }
    
    public void setMtgRmMeeting(MtgRmMeeting mtgRmMeeting) {
        this.mtgRmMeeting = mtgRmMeeting;
    }
    public int getAgendaNo() {
        return this.agendaNo;
    }
    
    public void setAgendaNo(int agendaNo) {
        this.agendaNo = agendaNo;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Set<MtgRmActionItemNote> getMtgRmActionItemNotes() {
        return this.mtgRmActionItemNotes;
    }
    
    public void setMtgRmActionItemNotes(Set<MtgRmActionItemNote> mtgRmActionItemNotes) {
        this.mtgRmActionItemNotes = mtgRmActionItemNotes;
    }
    public Set<MtgRmActionItemAssignee> getMtgRmActionItemAssignees() {
        return this.mtgRmActionItemAssignees;
    }
    
    public void setMtgRmActionItemAssignees(Set<MtgRmActionItemAssignee> mtgRmActionItemAssignees) {
        this.mtgRmActionItemAssignees = mtgRmActionItemAssignees;
    }




}



