/*
 * =============================================================================
 * Copyright 2010 Defence Science Technology Agency
 * 1 Depot Road, Defence Technology Tower A, Singapore 109679
 * All rights reserved.
 * =============================================================================
 * 
 * Project: Meeting Manager
 * Filename: MtgRmAgendaItemAttachment.java
 * Created on: 03.09.2010
 */

// Generated Sep 3, 2010 12:56:47 PM by Hibernate Tools 3.3.0.GA

package mtgmgr.entity;



/**
 * MtgRmAgendaItemAttachment generated by hbm2java
 */
public class MtgRmAgendaItemAttachment  implements java.io.Serializable {


     private int attachmentId;
     private MtgRmMeeting mtgRmMeeting;
     private int agendaNo;
     private String filename;

    public MtgRmAgendaItemAttachment() {
    }

    public MtgRmAgendaItemAttachment(int attachmentId, MtgRmMeeting mtgRmMeeting, int agendaNo, String filename) {
       this.attachmentId = attachmentId;
       this.mtgRmMeeting = mtgRmMeeting;
       this.agendaNo = agendaNo;
       this.filename = filename;
    }
   
    public int getAttachmentId() {
        return this.attachmentId;
    }
    
    public void setAttachmentId(int attachmentId) {
        this.attachmentId = attachmentId;
    }
    public MtgRmMeeting getMtgRmMeeting() {
        return this.mtgRmMeeting;
    }
    
    public void setMtgRmMeeting(MtgRmMeeting mtgRmMeeting) {
        this.mtgRmMeeting = mtgRmMeeting;
    }
    public int getAgendaNo() {
        return this.agendaNo;
    }
    
    public void setAgendaNo(int agendaNo) {
        this.agendaNo = agendaNo;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }




}



