/*
 * =============================================================================
 * Copyright 2010 Defence Science Technology Agency
 * 1 Depot Road, Defence Technology Tower A, Singapore 109679
 * All rights reserved.
 * =============================================================================
 * 
 * Project: Meeting Manager
 * Filename: MtgRmMeeting.java
 * Created on: 03.09.2010
 */

// Generated Sep 3, 2010 12:56:47 PM by Hibernate Tools 3.3.0.GA

package mtgmgr.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MtgRmMeeting generated by hbm2java
 */
public class MtgRmMeeting  implements java.io.Serializable {


     private int meetingId;
     private MtgRmList mtgRmList;
     private String name;
     private Date date;
     private Date startTime;
     private Date endTime;
     private String venue;
     private Date lastUpdated;
     private Set<MtgRmAgendaItem> mtgRmAgendaItems = new HashSet<MtgRmAgendaItem>(0);
     private Set<MtgRmAgendaItemAttachment> mtgRmAgendaItemAttachments = new HashSet<MtgRmAgendaItemAttachment>(0);
     private Set<MtgRmAgendaItemComment> mtgRmAgendaItemComments = new HashSet<MtgRmAgendaItemComment>(0);
     private Set<MtgRmActionItem> mtgRmActionItems = new HashSet<MtgRmActionItem>(0);

    public MtgRmMeeting() {
    }

	
    public MtgRmMeeting(int meetingId, MtgRmList mtgRmList, String name, Date date, Date startTime, Date endTime, String venue, Date lastUpdated) {
        this.meetingId = meetingId;
        this.mtgRmList = mtgRmList;
        this.name = name;
        this.date = date;
        this.startTime = startTime;
        this.endTime = endTime;
        this.venue = venue;
        this.lastUpdated = lastUpdated;
    }
    public MtgRmMeeting(int meetingId, MtgRmList mtgRmList, String name, Date date, Date startTime, Date endTime, String venue, Date lastUpdated, Set<MtgRmAgendaItem> mtgRmAgendaItems, Set<MtgRmAgendaItemAttachment> mtgRmAgendaItemAttachments, Set<MtgRmAgendaItemComment> mtgRmAgendaItemComments, Set<MtgRmActionItem> mtgRmActionItems) {
       this.meetingId = meetingId;
       this.mtgRmList = mtgRmList;
       this.name = name;
       this.date = date;
       this.startTime = startTime;
       this.endTime = endTime;
       this.venue = venue;
       this.lastUpdated = lastUpdated;
       this.mtgRmAgendaItems = mtgRmAgendaItems;
       this.mtgRmAgendaItemAttachments = mtgRmAgendaItemAttachments;
       this.mtgRmAgendaItemComments = mtgRmAgendaItemComments;
       this.mtgRmActionItems = mtgRmActionItems;
    }
   
    public int getMeetingId() {
        return this.meetingId;
    }
    
    public void setMeetingId(int meetingId) {
        this.meetingId = meetingId;
    }
    public MtgRmList getMtgRmList() {
        return this.mtgRmList;
    }
    
    public void setMtgRmList(MtgRmList mtgRmList) {
        this.mtgRmList = mtgRmList;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public String getVenue() {
        return this.venue;
    }
    
    public void setVenue(String venue) {
        this.venue = venue;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
    public Set<MtgRmAgendaItem> getMtgRmAgendaItems() {
        return this.mtgRmAgendaItems;
    }
    
    public void setMtgRmAgendaItems(Set<MtgRmAgendaItem> mtgRmAgendaItems) {
        this.mtgRmAgendaItems = mtgRmAgendaItems;
    }
    public Set<MtgRmAgendaItemAttachment> getMtgRmAgendaItemAttachments() {
        return this.mtgRmAgendaItemAttachments;
    }
    
    public void setMtgRmAgendaItemAttachments(Set<MtgRmAgendaItemAttachment> mtgRmAgendaItemAttachments) {
        this.mtgRmAgendaItemAttachments = mtgRmAgendaItemAttachments;
    }
    public Set<MtgRmAgendaItemComment> getMtgRmAgendaItemComments() {
        return this.mtgRmAgendaItemComments;
    }
    
    public void setMtgRmAgendaItemComments(Set<MtgRmAgendaItemComment> mtgRmAgendaItemComments) {
        this.mtgRmAgendaItemComments = mtgRmAgendaItemComments;
    }
    public Set<MtgRmActionItem> getMtgRmActionItems() {
        return this.mtgRmActionItems;
    }
    
    public void setMtgRmActionItems(Set<MtgRmActionItem> mtgRmActionItems) {
        this.mtgRmActionItems = mtgRmActionItems;
    }




}



