/*
 * =============================================================================
 * Copyright 2010 Defence Science Technology Agency
 * 1 Depot Road, Defence Technology Tower A, Singapore 109679
 * All rights reserved.
 * =============================================================================
 * 
 * Project: Meeting Manager
 * Filename: MtgRmMembershipId.java
 * Created on: 03.09.2010
 */

// Generated Sep 3, 2010 12:56:47 PM by Hibernate Tools 3.3.0.GA

package mtgmgr.entity;



/**
 * MtgRmMembershipId generated by hbm2java
 */
public class MtgRmMembershipId  implements java.io.Serializable {


     private int userid;
     private int mtgRmId;

    public MtgRmMembershipId() {
    }

    public MtgRmMembershipId(int userid, int mtgRmId) {
       this.userid = userid;
       this.mtgRmId = mtgRmId;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public int getMtgRmId() {
        return this.mtgRmId;
    }
    
    public void setMtgRmId(int mtgRmId) {
        this.mtgRmId = mtgRmId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MtgRmMembershipId) ) return false;
		 MtgRmMembershipId castOther = ( MtgRmMembershipId ) other; 
         
		 return (this.getUserid()==castOther.getUserid())
 && (this.getMtgRmId()==castOther.getMtgRmId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserid();
         result = 37 * result + this.getMtgRmId();
         return result;
   }   


}



