/*
 * =============================================================================
 * Copyright 2010 Defence Science Technology Agency
 * 1 Depot Road, Defence Technology Tower A, Singapore 109679
 * All rights reserved.
 * =============================================================================
 * 
 * Project: Meeting Manager
 * Filename: UserDirectory.java
 * Created on: 03.09.2010
 */

// Generated Sep 3, 2010 12:56:47 PM by Hibernate Tools 3.3.0.GA

package mtgmgr.entity;


import java.util.HashSet;
import java.util.Set;

/**
 * UserDirectory generated by hbm2java
 */
public class UserDirectory  implements java.io.Serializable {


     private int userid;
     private String username;
     private String password;
     private String emailAddress;
     private boolean isAdmin;
     private Set<MtgRmMembership> mtgRmMemberships = new HashSet<MtgRmMembership>(0);
     private Set<MtgRmAgendaItemComment> mtgRmAgendaItemComments = new HashSet<MtgRmAgendaItemComment>(0);
     private Set<MtgRmAgendaItem> mtgRmAgendaItems = new HashSet<MtgRmAgendaItem>(0);
     private Set<MtgRmActionItemNote> mtgRmActionItemNotes = new HashSet<MtgRmActionItemNote>(0);
     private Set<MtgRmActionItemAssignee> mtgRmActionItemAssignees = new HashSet<MtgRmActionItemAssignee>(0);
     private Set<GroupList> groupLists = new HashSet<GroupList>(0);

    public UserDirectory() {
    }

	
    public UserDirectory(int userid, String username, String password, boolean isAdmin) {
        this.userid = userid;
        this.username = username;
        this.password = password;
        this.isAdmin = isAdmin;
    }
    public UserDirectory(int userid, String username, String password, String emailAddress, boolean isAdmin, Set<MtgRmMembership> mtgRmMemberships, Set<MtgRmAgendaItemComment> mtgRmAgendaItemComments, Set<MtgRmAgendaItem> mtgRmAgendaItems, Set<MtgRmActionItemNote> mtgRmActionItemNotes, Set<MtgRmActionItemAssignee> mtgRmActionItemAssignees, Set<GroupList> groupLists) {
       this.userid = userid;
       this.username = username;
       this.password = password;
       this.emailAddress = emailAddress;
       this.isAdmin = isAdmin;
       this.mtgRmMemberships = mtgRmMemberships;
       this.mtgRmAgendaItemComments = mtgRmAgendaItemComments;
       this.mtgRmAgendaItems = mtgRmAgendaItems;
       this.mtgRmActionItemNotes = mtgRmActionItemNotes;
       this.mtgRmActionItemAssignees = mtgRmActionItemAssignees;
       this.groupLists = groupLists;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Set<MtgRmMembership> getMtgRmMemberships() {
        return this.mtgRmMemberships;
    }
    
    public void setMtgRmMemberships(Set<MtgRmMembership> mtgRmMemberships) {
        this.mtgRmMemberships = mtgRmMemberships;
    }
    public Set<MtgRmAgendaItemComment> getMtgRmAgendaItemComments() {
        return this.mtgRmAgendaItemComments;
    }
    
    public void setMtgRmAgendaItemComments(Set<MtgRmAgendaItemComment> mtgRmAgendaItemComments) {
        this.mtgRmAgendaItemComments = mtgRmAgendaItemComments;
    }
    public Set<MtgRmAgendaItem> getMtgRmAgendaItems() {
        return this.mtgRmAgendaItems;
    }
    
    public void setMtgRmAgendaItems(Set<MtgRmAgendaItem> mtgRmAgendaItems) {
        this.mtgRmAgendaItems = mtgRmAgendaItems;
    }
    public Set<MtgRmActionItemNote> getMtgRmActionItemNotes() {
        return this.mtgRmActionItemNotes;
    }
    
    public void setMtgRmActionItemNotes(Set<MtgRmActionItemNote> mtgRmActionItemNotes) {
        this.mtgRmActionItemNotes = mtgRmActionItemNotes;
    }
    public Set<MtgRmActionItemAssignee> getMtgRmActionItemAssignees() {
        return this.mtgRmActionItemAssignees;
    }
    
    public void setMtgRmActionItemAssignees(Set<MtgRmActionItemAssignee> mtgRmActionItemAssignees) {
        this.mtgRmActionItemAssignees = mtgRmActionItemAssignees;
    }
    public Set<GroupList> getGroupLists() {
        return this.groupLists;
    }
    
    public void setGroupLists(Set<GroupList> groupLists) {
        this.groupLists = groupLists;
    }




}



