package mtgmgr.entity;
// Generated Aug 27, 2010 11:18:15 AM by Hibernate Tools 3.3.0.GA



/**
 * GroupMtgRmMembership generated by hbm2java
 */
public class GroupMtgRmMembership  implements java.io.Serializable {


     private GroupMtgRmMembershipId id;
     private MtgRmList mtgRmList;
     private GroupList groupList;
     private String role;

    public GroupMtgRmMembership() {
    }

    public GroupMtgRmMembership(GroupMtgRmMembershipId id, MtgRmList mtgRmList, GroupList groupList, String role) {
       this.id = id;
       this.mtgRmList = mtgRmList;
       this.groupList = groupList;
       this.role = role;
    }
   
    public GroupMtgRmMembershipId getId() {
        return this.id;
    }
    
    public void setId(GroupMtgRmMembershipId id) {
        this.id = id;
    }
    public MtgRmList getMtgRmList() {
        return this.mtgRmList;
    }
    
    public void setMtgRmList(MtgRmList mtgRmList) {
        this.mtgRmList = mtgRmList;
    }
    public GroupList getGroupList() {
        return this.groupList;
    }
    
    public void setGroupList(GroupList groupList) {
        this.groupList = groupList;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


