package mtgmgr.entity;
// Generated Aug 27, 2010 11:18:15 AM by Hibernate Tools 3.3.0.GA



/**
 * MtgRmActionItemAssignee generated by hbm2java
 */
public class MtgRmActionItemAssignee  implements java.io.Serializable {


     private int assigneeId;
     private MtgRmActionItem mtgRmActionItem;
     private UserDirectory userDirectory;

    public MtgRmActionItemAssignee() {
    }

    public MtgRmActionItemAssignee(int assigneeId, MtgRmActionItem mtgRmActionItem, UserDirectory userDirectory) {
       this.assigneeId = assigneeId;
       this.mtgRmActionItem = mtgRmActionItem;
       this.userDirectory = userDirectory;
    }
   
    public int getAssigneeId() {
        return this.assigneeId;
    }
    
    public void setAssigneeId(int assigneeId) {
        this.assigneeId = assigneeId;
    }
    public MtgRmActionItem getMtgRmActionItem() {
        return this.mtgRmActionItem;
    }
    
    public void setMtgRmActionItem(MtgRmActionItem mtgRmActionItem) {
        this.mtgRmActionItem = mtgRmActionItem;
    }
    public UserDirectory getUserDirectory() {
        return this.userDirectory;
    }
    
    public void setUserDirectory(UserDirectory userDirectory) {
        this.userDirectory = userDirectory;
    }




}


