package mtgmgr.entity;
// Generated Aug 27, 2010 11:18:15 AM by Hibernate Tools 3.3.0.GA



/**
 * MtgRmMembership generated by hbm2java
 */
public class MtgRmMembership  implements java.io.Serializable {


     private MtgRmMembershipId id;
     private MtgRmList mtgRmList;
     private UserDirectory userDirectory;
     private String role;

    public MtgRmMembership() {
    }

    public MtgRmMembership(MtgRmMembershipId id, MtgRmList mtgRmList, UserDirectory userDirectory, String role) {
       this.id = id;
       this.mtgRmList = mtgRmList;
       this.userDirectory = userDirectory;
       this.role = role;
    }
   
    public MtgRmMembershipId getId() {
        return this.id;
    }
    
    public void setId(MtgRmMembershipId id) {
        this.id = id;
    }
    public MtgRmList getMtgRmList() {
        return this.mtgRmList;
    }
    
    public void setMtgRmList(MtgRmList mtgRmList) {
        this.mtgRmList = mtgRmList;
    }
    public UserDirectory getUserDirectory() {
        return this.userDirectory;
    }
    
    public void setUserDirectory(UserDirectory userDirectory) {
        this.userDirectory = userDirectory;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


