package mtgmgr.entity;
// Generated Aug 27, 2010 11:18:15 AM by Hibernate Tools 3.3.0.GA


import java.util.Date;

/**
 * MtgRmAgendaItemComment generated by hbm2java
 */
public class MtgRmAgendaItemComment  implements java.io.Serializable {


     private MtgRmAgendaItemCommentId id;
     private MtgRmMeeting mtgRmMeeting;
     private UserDirectory userDirectory;
     private Date datetime;
     private String content;

    public MtgRmAgendaItemComment() {
    }

    public MtgRmAgendaItemComment(MtgRmAgendaItemCommentId id, MtgRmMeeting mtgRmMeeting, UserDirectory userDirectory, Date datetime, String content) {
       this.id = id;
       this.mtgRmMeeting = mtgRmMeeting;
       this.userDirectory = userDirectory;
       this.datetime = datetime;
       this.content = content;
    }
   
    public MtgRmAgendaItemCommentId getId() {
        return this.id;
    }
    
    public void setId(MtgRmAgendaItemCommentId id) {
        this.id = id;
    }
    public MtgRmMeeting getMtgRmMeeting() {
        return this.mtgRmMeeting;
    }
    
    public void setMtgRmMeeting(MtgRmMeeting mtgRmMeeting) {
        this.mtgRmMeeting = mtgRmMeeting;
    }
    public UserDirectory getUserDirectory() {
        return this.userDirectory;
    }
    
    public void setUserDirectory(UserDirectory userDirectory) {
        this.userDirectory = userDirectory;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


