package mtgmgr.entity;
// Generated Aug 27, 2010 11:18:15 AM by Hibernate Tools 3.3.0.GA


import java.util.Date;

/**
 * MtgRmAgendaItem generated by hbm2java
 */
public class MtgRmAgendaItem  implements java.io.Serializable {


     private MtgRmAgendaItemId id;
     private UserDirectory userDirectory;
     private MtgRmMeeting mtgRmMeeting;
     private String item;
     private String staff;
     private String synopsis;
     private Date duration;
     private String log;

    public MtgRmAgendaItem() {
    }

	
    public MtgRmAgendaItem(MtgRmAgendaItemId id, UserDirectory userDirectory, MtgRmMeeting mtgRmMeeting, String item, String synopsis, Date duration) {
        this.id = id;
        this.userDirectory = userDirectory;
        this.mtgRmMeeting = mtgRmMeeting;
        this.item = item;
        this.synopsis = synopsis;
        this.duration = duration;
    }
    public MtgRmAgendaItem(MtgRmAgendaItemId id, UserDirectory userDirectory, MtgRmMeeting mtgRmMeeting, String item, String staff, String synopsis, Date duration, String log) {
       this.id = id;
       this.userDirectory = userDirectory;
       this.mtgRmMeeting = mtgRmMeeting;
       this.item = item;
       this.staff = staff;
       this.synopsis = synopsis;
       this.duration = duration;
       this.log = log;
    }
   
    public MtgRmAgendaItemId getId() {
        return this.id;
    }
    
    public void setId(MtgRmAgendaItemId id) {
        this.id = id;
    }
    public UserDirectory getUserDirectory() {
        return this.userDirectory;
    }
    
    public void setUserDirectory(UserDirectory userDirectory) {
        this.userDirectory = userDirectory;
    }
    public MtgRmMeeting getMtgRmMeeting() {
        return this.mtgRmMeeting;
    }
    
    public void setMtgRmMeeting(MtgRmMeeting mtgRmMeeting) {
        this.mtgRmMeeting = mtgRmMeeting;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public String getStaff() {
        return this.staff;
    }
    
    public void setStaff(String staff) {
        this.staff = staff;
    }
    public String getSynopsis() {
        return this.synopsis;
    }
    
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }
    public Date getDuration() {
        return this.duration;
    }
    
    public void setDuration(Date duration) {
        this.duration = duration;
    }
    public String getLog() {
        return this.log;
    }
    
    public void setLog(String log) {
        this.log = log;
    }




}


