package mtgmgr.entity;
// Generated Aug 27, 2010 11:18:15 AM by Hibernate Tools 3.3.0.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MtgRmList generated by hbm2java
 */
public class MtgRmList  implements java.io.Serializable {


     private int mtgRmId;
     private String name;
     private String category;
     private String tor;
     private Set<MtgRmMembership> mtgRmMemberships = new HashSet<MtgRmMembership>(0);
     private Set<MtgRmMeeting> mtgRmMeetings = new HashSet<MtgRmMeeting>(0);
     private Set<GroupMtgRmMembership> groupMtgRmMemberships = new HashSet<GroupMtgRmMembership>(0);

    public MtgRmList() {
    }

	
    public MtgRmList(int mtgRmId, String name, String category) {
        this.mtgRmId = mtgRmId;
        this.name = name;
        this.category = category;
    }
    public MtgRmList(int mtgRmId, String name, String category, String tor, Set<MtgRmMembership> mtgRmMemberships, Set<MtgRmMeeting> mtgRmMeetings, Set<GroupMtgRmMembership> groupMtgRmMemberships) {
       this.mtgRmId = mtgRmId;
       this.name = name;
       this.category = category;
       this.tor = tor;
       this.mtgRmMemberships = mtgRmMemberships;
       this.mtgRmMeetings = mtgRmMeetings;
       this.groupMtgRmMemberships = groupMtgRmMemberships;
    }
   
    public int getMtgRmId() {
        return this.mtgRmId;
    }
    
    public void setMtgRmId(int mtgRmId) {
        this.mtgRmId = mtgRmId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getTor() {
        return this.tor;
    }
    
    public void setTor(String tor) {
        this.tor = tor;
    }
    public Set<MtgRmMembership> getMtgRmMemberships() {
        return this.mtgRmMemberships;
    }
    
    public void setMtgRmMemberships(Set<MtgRmMembership> mtgRmMemberships) {
        this.mtgRmMemberships = mtgRmMemberships;
    }
    public Set<MtgRmMeeting> getMtgRmMeetings() {
        return this.mtgRmMeetings;
    }
    
    public void setMtgRmMeetings(Set<MtgRmMeeting> mtgRmMeetings) {
        this.mtgRmMeetings = mtgRmMeetings;
    }
    public Set<GroupMtgRmMembership> getGroupMtgRmMemberships() {
        return this.groupMtgRmMemberships;
    }
    
    public void setGroupMtgRmMemberships(Set<GroupMtgRmMembership> groupMtgRmMemberships) {
        this.groupMtgRmMemberships = groupMtgRmMemberships;
    }




}


