package mtgmgr.entity;
// Generated Aug 27, 2010 11:18:15 AM by Hibernate Tools 3.3.0.GA



/**
 * MtgRmAgendaItemAttachment generated by hbm2java
 */
public class MtgRmAgendaItemAttachment  implements java.io.Serializable {


     private int attachmentId;
     private MtgRmMeeting mtgRmMeeting;
     private int agendaNo;
     private String filename;

    public MtgRmAgendaItemAttachment() {
    }

    public MtgRmAgendaItemAttachment(int attachmentId, MtgRmMeeting mtgRmMeeting, int agendaNo, String filename) {
       this.attachmentId = attachmentId;
       this.mtgRmMeeting = mtgRmMeeting;
       this.agendaNo = agendaNo;
       this.filename = filename;
    }
   
    public int getAttachmentId() {
        return this.attachmentId;
    }
    
    public void setAttachmentId(int attachmentId) {
        this.attachmentId = attachmentId;
    }
    public MtgRmMeeting getMtgRmMeeting() {
        return this.mtgRmMeeting;
    }
    
    public void setMtgRmMeeting(MtgRmMeeting mtgRmMeeting) {
        this.mtgRmMeeting = mtgRmMeeting;
    }
    public int getAgendaNo() {
        return this.agendaNo;
    }
    
    public void setAgendaNo(int agendaNo) {
        this.agendaNo = agendaNo;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }




}


