package mtgmgr.entity;
// Generated Aug 27, 2010 11:18:15 AM by Hibernate Tools 3.3.0.GA



/**
 * MtgRmAgendaItemCommentId generated by hbm2java
 */
public class MtgRmAgendaItemCommentId  implements java.io.Serializable {


     private int meetingId;
     private int agendaNo;
     private int commentNo;

    public MtgRmAgendaItemCommentId() {
    }

    public MtgRmAgendaItemCommentId(int meetingId, int agendaNo, int commentNo) {
       this.meetingId = meetingId;
       this.agendaNo = agendaNo;
       this.commentNo = commentNo;
    }
   
    public int getMeetingId() {
        return this.meetingId;
    }
    
    public void setMeetingId(int meetingId) {
        this.meetingId = meetingId;
    }
    public int getAgendaNo() {
        return this.agendaNo;
    }
    
    public void setAgendaNo(int agendaNo) {
        this.agendaNo = agendaNo;
    }
    public int getCommentNo() {
        return this.commentNo;
    }
    
    public void setCommentNo(int commentNo) {
        this.commentNo = commentNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MtgRmAgendaItemCommentId) ) return false;
		 MtgRmAgendaItemCommentId castOther = ( MtgRmAgendaItemCommentId ) other; 
         
		 return (this.getMeetingId()==castOther.getMeetingId())
 && (this.getAgendaNo()==castOther.getAgendaNo())
 && (this.getCommentNo()==castOther.getCommentNo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMeetingId();
         result = 37 * result + this.getAgendaNo();
         result = 37 * result + this.getCommentNo();
         return result;
   }   


}


