package mtgmgr.entity;
// Generated Aug 27, 2010 11:18:15 AM by Hibernate Tools 3.3.0.GA



/**
 * MtgRmActionItemNoteId generated by hbm2java
 */
public class MtgRmActionItemNoteId  implements java.io.Serializable {


     private int actionItemId;
     private int commentNo;

    public MtgRmActionItemNoteId() {
    }

    public MtgRmActionItemNoteId(int actionItemId, int commentNo) {
       this.actionItemId = actionItemId;
       this.commentNo = commentNo;
    }
   
    public int getActionItemId() {
        return this.actionItemId;
    }
    
    public void setActionItemId(int actionItemId) {
        this.actionItemId = actionItemId;
    }
    public int getCommentNo() {
        return this.commentNo;
    }
    
    public void setCommentNo(int commentNo) {
        this.commentNo = commentNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MtgRmActionItemNoteId) ) return false;
		 MtgRmActionItemNoteId castOther = ( MtgRmActionItemNoteId ) other; 
         
		 return (this.getActionItemId()==castOther.getActionItemId())
 && (this.getCommentNo()==castOther.getCommentNo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getActionItemId();
         result = 37 * result + this.getCommentNo();
         return result;
   }   


}


