CREATE TABLE IF NOT EXISTS `GROUP_HIERARCHY` (
  `PARENT_GROUP_ID` int(15) NOT NULL,
  `CHILD_GROUP_ID` int(15) NOT NULL,
  `CREATION_DATE` date NOT NULL DEFAULT '1000-01-01',
  `MODIFIED_DATE` date NOT NULL DEFAULT '1000-01-01',
  PRIMARY KEY (`PARENT_GROUP_ID`, `CHILD_GROUP_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `GROUP_SECURITY` (
  `GROUP_ID`       int(15)   NOT NULL,
  `GROUP_NAME`     VARCHAR(200)  NOT NULL,
  `CREATION_DATE`  date NOT NULL DEFAULT '1000-01-01',
  `MODIFIED_DATE`  date NOT NULL DEFAULT '1000-01-01',
  PRIMARY KEY ( `GROUP_ID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_ACCESS_CONTROL` (
  `USER_NO`                int(20)   NOT NULL,
  `USER_ID`                VARCHAR(200),
  `USER_NAME`              VARCHAR(200),
  `USER_ACCESS_LEVEL`      VARCHAR(200),
  `USER_COMMITTEE_ACCESS`  VARCHAR(400),
  PRIMARY KEY ( `USER_NO` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_ACTIONITEM` (
  `ID`             int( 38 ) NOT NULL,
  `NAME`           VARCHAR(255)  NOT NULL,
  `PROGRESS`       VARCHAR(4000),
  `STATUS`         VARCHAR(10),
  `COMMENTS`       VARCHAR(4000),
  `DATEUPDATED`    DATE,
  `UPDATEDBY`      VARCHAR(80),
  `MEETINGID`      int( 38 ) NOT NULL,
  `DATECREATED`    DATE,
  `CREATEDBY`      VARCHAR(80),
  `SEC_IN_CHARGE`  VARCHAR(4000),
  PRIMARY KEY ( `ID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_AGENDAITEM` (
  `ID`                 int( 38 ) NOT NULL,
  `NAME`               VARCHAR(200)  NOT NULL,
  `ITEMORDER`          VARCHAR(5),
  `STATUS`             VARCHAR(20),
  `DEPARTMENT`         VARCHAR(50),
  `REMARKS`            VARCHAR(4000),
  `SUBMITTEDBY`        VARCHAR(80),
  `DATESUBMITTED`      DATE,
  `MEETINGID`          int( 38 ),
  `STARTTIME`          VARCHAR(5),
  `UPDATEDBY`          VARCHAR(80),
  `DATEUPDATED`        DATE,
  `SUBMITTEDBYUSERID`  int( 38 ),
  `FORUMID`            int( 38 ),
  `MINUTES`            VARCHAR(4000),
  `REMARK2`            VARCHAR(4000),
  `PURPOSE`            VARCHAR(1500),
  PRIMARY KEY ( `ID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_AGENDA_ACTION_LINK` (
  `AGENDAITEMID`  int(38)   NOT NULL,
  `ACTIONITEMID`  int(38)   NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_ATTENDANCE` (
  `USERID`         int( 38 ) NOT NULL,
  `MEETINGID`      int( 38 ) NOT NULL,
  `STATUS`         VARCHAR(1),
  `REPRESENTEDBY`  VARCHAR(80),
  PRIMARY KEY ( `USERID`, `MEETINGID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_ATTENDANCE_GROUP` (
  `MEETINGID`    int( 38 ) NOT NULL,
  `USERGROUPID`  int( 38 ) NOT NULL,
  PRIMARY KEY ( `MEETINGID`, `USERGROUPID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_DOMAIN` (
  `DOMAIN_ID`    int(11)   NOT NULL,
  `DOMAIN_NAME`  VARCHAR(4000),
  `DOMAIN_DESC`  VARCHAR(4000),
  `DOMAIN_URL`   VARCHAR(4000),
  PRIMARY KEY ( `DOMAIN_ID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_FORUM` (
  `ID`                         int( 38 ) NOT NULL,
  `NAME`                       VARCHAR(100)  NOT NULL,
  `DESCRIPTION`                VARCHAR(1000),
  `DATEUPDATED`                DATE,
  `UPDATEDBY`                  VARCHAR(80),
  `TOR`                        VARCHAR(1000),
  `FOLDERID`                   int( 38 ),
  `SECRETARIATCONTACTGROUPID`  int( 38 ),
  `OPENFORUM`                  VARCHAR(1),
  `DATECREATED`                DATE,
  `CREATEDBY`                  VARCHAR(80),
  `CONTACT`                    VARCHAR(1000),
  `MEMBERSHIP_URL`             VARCHAR(1000),
  `DOMAIN_ID`                  int(11),
  `EROOM_URL`                  VARCHAR(1000),
  `FLAG1`                      CHAR (1)      DEFAULT 'N'
 NOT NULL,
  `WIKI_URL`                   VARCHAR(1000),
  `GLOSSARY_URL`               VARCHAR(1000),
  `CDMSFOLDERID`               VARCHAR(50),
  `SENDNOTIFYISSUEEMAIL`       VARCHAR(4),
  PRIMARY KEY ( `ID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_FORUM_BK` (
  `ID`                         int( 38 ) NOT NULL,
  `NAME`                       VARCHAR(100)  NOT NULL,
  `DESCRIPTION`                VARCHAR(1000),
  `DATEUPDATED`                DATE,
  `UPDATEDBY`                  VARCHAR(80),
  `TOR`                        VARCHAR(1000),
  `FOLDERID`                   int( 38 ),
  `SECRETARIATCONTACTGROUPID`  int( 38 ),
  `OPENFORUM`                  VARCHAR(1),
  `DATECREATED`                DATE,
  `CREATEDBY`                  VARCHAR(80),
  `CONTACT`                    VARCHAR(1000),
  `MEMBERSHIP_URL`             VARCHAR(1000),
  `DOMAIN_ID`                  int(11),
  `EROOM_URL`                  VARCHAR(1000),
  `FLAG1`                      CHAR (1)      NOT NULL,
  `WIKI_URL`                   VARCHAR(1000),
  `GLOSSARY_URL`               VARCHAR(1000),
  `CDMSFOLDERID`               VARCHAR(50)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_LOGBOOK` (
  `ID`            int( 38 ) NOT NULL,
  `TITLE`         VARCHAR(4000),
  `ACTIVITYLOG`   VARCHAR(4000),
  `CREATOR`       VARCHAR(500),
  `CREATIONDATE`  DATE,
  `UPDATEDBY`     VARCHAR(500),
  `LASTUPDATED`   DATE,
  `EXTRA`         VARCHAR(4000),
  `FORUMID`       int( 38 ),
  `CREATORID`     int( 38 )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_MEETING` (
  `ID`                       int( 38 ) NOT NULL,
  `NAME`                     VARCHAR(100)  NOT NULL,
  `MEETINGDATE`              DATE,
  `STARTTIME`                VARCHAR(5),
  `ENDTIME`                  VARCHAR(5),
  `VENUE`                    VARCHAR(100),
  `ANNOUNCEMENTS`            VARCHAR(4000),
  `FORUMID`                  int( 38 ) NOT NULL,
  `DATEUPDATED`              DATE,
  `FOLDERID`                 int( 38 ),
  `HTMLDOCID`                int( 38 ),
  `UPDATEDBY`                VARCHAR(80),
  `CREATEDBY`                VARCHAR(80),
  `DATECREATED`              DATE,
  `AGENDA_TITLE`             VARCHAR(1000),
  `AGENDA_URL`               VARCHAR(1000),
  `MEETING_MATERIALS_TITLE`  VARCHAR(1000),
  `MEETING_MATERIALS_URL`    VARCHAR(1000),
  `MINUTES_TITLE`            VARCHAR(1000),
  `MINUTES_URL`              VARCHAR(1000),
  `PREVIOUS_MINUTES_TITLE`   VARCHAR(1000),
  `PREVIOUS_MINUTES_URL`     VARCHAR(1000),
  `DOMAIN_ID`                int(11),
  PRIMARY KEY ( `ID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_MEMBERSHIP` (
  `FORUMID`        int( 38 ),
  `USERGROUPID`    int( 38 ),
  `ROLE`           VARCHAR(100),
  `TOR`            VARCHAR(1),
  `TYPE`           VARCHAR(1),
  `USERGROUPNAME`  VARCHAR(150)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_MYACTIONITEM` (
  `ACTIONITEMID`  int( 38 ) NOT NULL,
  `USERID`        int( 38 ) NOT NULL,
  `USERNAME`      VARCHAR(150)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_MYSUBSCRIPTION` (
  `FORUMID`  int( 38 ) NOT NULL,
  `USERID`   int( 38 ) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_PAPER` (
  `ID`                int( 38 ) NOT NULL,
  `NAME`              VARCHAR(200)  NOT NULL,
  `URL`               VARCHAR(400)  NOT NULL,
  `TYPE`              VARCHAR(1)  NOT NULL,
  `AGENDAITEMID`      int( 38 ),
  `MEETINGID`         int( 38 ),
  `DOCTYPEIMAGEUUID`  VARCHAR(50),
  `PARENTID`          int( 38 ),
  `PARENTTYPE`        VARCHAR(50),
  PRIMARY KEY ( `ID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_SECONDARYASSIGNEE` (
  `ACTIONITEMID`  int( 38 ) NOT NULL,
  `USERID`        int( 38 ) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_STATS` (
  `ENTITYID`  int(38)   NOT NULL,
  `TYPE`      VARCHAR(4000)  NOT NULL,
  `MONTH`     int(38)   NOT NULL,
  `YEAR`      int(38)   NOT NULL,
  `HITS`      int(38)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_STATS_2` (
  `ENTITYID`  int( 38 ) NOT NULL,
  `TYPE`      VARCHAR(4000)  NOT NULL,
  `HITS`      int( 38 )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_UPDATES` (
  `ITEM_TYPE`       VARCHAR(500)  NOT NULL,
  `ITEM_ID`         int(38)   NOT NULL,
  `UPDATE_CONTENT`  VARCHAR(4000),
  `UPDATE_DATE`     DATE          NOT NULL,
  `UPDATE_OWNER`    VARCHAR(50)  NOT NULL,
  `UPDATE_TYPE`     VARCHAR(4000)  NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_USER_PROFILE` (
  `USERID`        int( 38 ) NOT NULL,
  `USERLOGIN`     VARCHAR(50)  NOT NULL,
  `USERFULLNAME`  VARCHAR(100),
  PRIMARY KEY ( `USERID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_WORKSPACE` (
  `ID`              int(38)   NOT NULL,
  `MESSAGE`         VARCHAR(4000),
  `CREATEDBY`       VARCHAR(500),
  `DATECREATED`     DATE,
  `FORUMID`         int(38),
  `TYPE`            VARCHAR(500),
  `TYPEID`          int(38),
  `SUBJECT`         VARCHAR(4000),
  `PRIVATECOMMENT`  VARCHAR(4)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `MTG_WORKSPACE_BK` (
  `ID`           int( 38 ) NOT NULL,
  `MESSAGE`      VARCHAR(4000),
  `CREATEDBY`    VARCHAR(500),
  `DATECREATED`  DATE,
  `FORUMID`      int( 38 ),
  `TYPE`         VARCHAR(500),
  `TYPEID`       int( 38 ),
  `SUBJECT`      VARCHAR(4000)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `USER_GROUP_CACHE` (
  `USER_NAME`   VARCHAR(100)  NOT NULL,
  `GROUP_NAME`  VARCHAR(100)  NOT NULL,
  PRIMARY KEY ( `USER_NAME`, `GROUP_NAME` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `USER_GROUP_HIERARCHY` (
  `GROUP_ID`       int(15)   NOT NULL,
  `USER_ID`        int(15)   NOT NULL,
  `CREATION_DATE`  date NOT NULL DEFAULT '1000-01-01',
  `MODIFIED_DATE`  date NOT NULL DEFAULT '1000-01-01',
  PRIMARY KEY ( `GROUP_ID`, `USER_ID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `USER_PROFILE` (
  `USER_NAME`      VARCHAR(200)  NOT NULL,
  `PROFILE_TYPE`   VARCHAR(100)  NOT NULL,
  `CREATION_DATE`  date NOT NULL DEFAULT '1000-01-01',
  PRIMARY KEY ( `USER_NAME` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `USER_SECURITY` (
  `USER_ID`        int(15)   NOT NULL,
  `PASSWORD`       VARCHAR(50),
  `USER_NAME`      VARCHAR(200)  NOT NULL,
  `CREATION_DATE`  date NOT NULL DEFAULT '1000-01-01',
  `MODIFIED_DATE`  date NOT NULL DEFAULT '1000-01-01',
  PRIMARY KEY ( `USER_ID` )
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*-----*/
ALTER TABLE GROUP_HIERARCHY ADD CONSTRAINT FK1_GROUP_HRCHY
 FOREIGN KEY (PARENT_GROUP_ID) 
  REFERENCES MGTPORTAL.GROUP_SECURITY (GROUP_ID) 
 ON DELETE CASCADE;
ALTER TABLE GROUP_HIERARCHY ADD CONSTRAINT FK2_GROUP_HRCHY
 FOREIGN KEY (CHILD_GROUP_ID) 
  REFERENCES MGTPORTAL.GROUP_SECURITY (GROUP_ID) ;
ALTER TABLE MTG_AGENDA_ACTION_LINK ADD CONSTRAINT FK_LINK_ACTIONITEM
 FOREIGN KEY (ACTIONITEMID) 
  REFERENCES MGTPORTAL.MTG_ACTIONITEM (ID) 
 ON DELETE CASCADE;
ALTER TABLE MTG_AGENDA_ACTION_LINK ADD CONSTRAINT FK_LINK_AGENDAITEM
 FOREIGN KEY (AGENDAITEMID) 
  REFERENCES MGTPORTAL.MTG_AGENDAITEM (ID) 
 ON DELETE CASCADE;
ALTER TABLE MTG_ATTENDANCE ADD CONSTRAINT FK_MTG_ATTENDANCE_MEETINGID
 FOREIGN KEY (MEETINGID) 
  REFERENCES MGTPORTAL.MTG_MEETING (ID) 
 ON DELETE CASCADE;
ALTER TABLE MTG_ATTENDANCE ADD CONSTRAINT FK_MTG_ATTENDANCE_USERID
 FOREIGN KEY (USERID) 
  REFERENCES MGTPORTAL.MTG_USER_PROFILE (USERID) 
 ON DELETE CASCADE;
ALTER TABLE MTG_ATTENDANCE_GROUP ADD CONSTRAINT FK_ATTENDANCE_GRP_MEETINGID
 FOREIGN KEY (MEETINGID) 
  REFERENCES MGTPORTAL.MTG_MEETING (ID) 
 ON DELETE CASCADE;
ALTER TABLE MTG_ATTENDANCE_GROUP ADD CONSTRAINT FK_ATTENDANCE_GRP_USERGROUPID
 FOREIGN KEY (USERGROUPID) 
  REFERENCES MGTPORTAL.GROUP_SECURITY (GROUP_ID) 
 ON DELETE CASCADE;
ALTER TABLE USER_GROUP_HIERARCHY ADD CONSTRAINT FK1_USER_G_HRCHY
 FOREIGN KEY (USER_ID) 
  REFERENCES MGTPORTAL.USER_SECURITY (USER_ID) 
 ON DELETE CASCADE;
ALTER TABLE USER_GROUP_HIERARCHY ADD CONSTRAINT FK2_USER_G_HRCHY
 FOREIGN KEY (GROUP_ID) 
  REFERENCES MGTPORTAL.GROUP_SECURITY (GROUP_ID) 
 ON DELETE CASCADE;
/*-----*/
GRANT SELECT ON MTG_DOMAIN TO KMCAPPL_SEARCH;
GRANT SELECT ON MTG_FORUM TO KMCAPPL_SEARCH;
GRANT SELECT ON MTG_MEETING TO KMCAPPL_SEARCH;
/*-----*/
DROP TRIGGER IF EXISTS TU_GROUP_HRCHY;
CREATE TRIGGER TU_GROUP_HRCHY
  BEFORE UPDATE
  on GROUP_HIERARCHY
  FOR EACH ROW
/* :NEW.MODIFIED_DATE := SYSDATE; */
 SET NEW.MODIFIED_DATE = '1000-01-01';
DROP TRIGGER IF EXISTS TU_GROUP_SEC;
CREATE TRIGGER TU_GROUP_SEC
  BEFORE UPDATE
  on GROUP_SECURITY
  FOR EACH ROW
/* :NEW.MODIFIED_DATE := SYSDATE; */
 SET NEW.MODIFIED_DATE = '1000-01-01';
DROP TRIGGER IF EXISTS admin_trigger;
CREATE TRIGGER admin_trigger 
before insert on MTG_Access_control 
  FOR EACH ROW
/* select meeting_seq.nextval into :new.user_no from dual; */
DROP TRIGGER IF EXISTS domains_trigger;
CREATE TRIGGER domains_trigger 
before insert on MTG_DOMAIN 
  FOR EACH ROW
/* select meeting_seq.nextval into :new.domain_id from dual; */
DROP TRIGGER IF EXISTS TU_USER_G_HRCHY;
CREATE TRIGGER TU_USER_G_HRCHY
  BEFORE UPDATE
  on USER_GROUP_HIERARCHY
  FOR EACH ROW
/* :NEW.MODIFIED_DATE := SYSDATE; */
 SET NEW.MODIFIED_DATE = '1000-01-01';
DROP TRIGGER IF EXISTS TU_USER_SEC;
CREATE TRIGGER TU_USER_SEC
  BEFORE UPDATE
  on USER_SECURITY
  FOR EACH ROW
/* :NEW.MODIFIED_DATE := SYSDATE; */
 SET NEW.MODIFIED_DATE = '1000-01-01';
/*-----*/
--DROP INDEX IX1_GROUP_HRCHY ON GROUP_HIERARCHY;
CREATE UNIQUE INDEX IX1_GROUP_HRCHY ON GROUP_HIERARCHY(CHILD_GROUP_ID, PARENT_GROUP_ID);
--DROP INDEX AX1_GROUP_SEC ON GROUP_SECURITY;
CREATE UNIQUE INDEX AX1_GROUP_SEC ON GROUP_SECURITY(GROUP_NAME);
--DROP INDEX IX1_USER_G_HRCHY ON USER_GROUP_HIERARCHY;
CREATE UNIQUE INDEX IX1_USER_G_HRCHY ON USER_GROUP_HIERARCHY(USER_ID, GROUP_ID);
--DROP INDEX AX1_USER_SEC ON USER_SECURITY;
CREATE UNIQUE INDEX AX1_USER_SEC ON USER_SECURITY(USER_NAME);
/*-----*/